version: '3.4'

services:
  jam.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  user.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

